### ISSUE TITLE
Any chance of a .NET Standard port?

### ISSUE THREAD

**Issue by BrianVallelunga** [mikoskinen/NSQLFormatter-dotnet#1]
This is a handy library. Any chance you could update it to be compatible with .NET Standard and release a new Nuget package? I'd be happy to give that a try myself. I think it should be pretty easy since you have no dependencies.

**Comment by mikoskinen** [comment]
I'm sorry for the slow response. I've just published a 2.0.0 version of the NuGet package, which adds .NET Standard 1.3 support.
